### ISSUE TITLE
Encode() will panic if struct contain field of struct pointer

### ISSUE THREAD

**Issue by kurtzhong** [gorilla/schema#87]
Seems like this package doesn't allow struct to contain ***struct** field. Is there any plan to support this?

Here the code that triggers panic: 

![image](https://user-images.githubusercontent.com/735693/29404714-59a9e37a-836e-11e7-9b89-904b60383f1c.png)

Here is the panic message: 

```
--- FAIL: TestSlices (0.00s)
exit status 2
FAIL	example.com/x/vendor/github.com/gorilla/schema	0.010s
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation, code=0x1 addr=0x0 pc=0x111e298]

goroutine 6 [running]:
testing.tRunner.func1(0xc420074750)
	/usr/local/Cellar/go/1.8.1/libexec/src/testing/testing.go:622 +0x29d
panic(,0x1145d40, 0x1216840)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/panic.go:,489 +0x2cf
example.com/x/vendor/github.com/gorilla/schema.typeEncoder.func1(0x1131640, 0xc42001ea70, 0x1b6, 0x5, 0x1131640)
	/Users/kurt/gopath/src/example.com/x/vendor/github.com/gorilla/schema/encoder.go:117 +0xb8
example.com/x/vendor/github.com/gorilla/schema.(*Encoder).encode(0xc4200132b0, 0x1135740, 0xc42001ea00, 0x16, 0xc42000eb40, 0xc420013280, 0xc4200132c0)
	/Users/kurt/gopath/src/example.com/x/vendor/github.com/gorilla/schema/encoder.go:63 +0x433
,example.com/x/vendor/github.com/gorilla/schema.(*Encoder).Encode(0xc4200132b0, 0x1135740, 0xc42001ea00, 0xc42000eb40,, 0xc42000eb40, 0xc420022000)
	/Users/kurt/gopath/src/example.com/x/vendor/github.com/gorilla/schema/encoder.go:,29 +0x6b
example.com/x/vendor/github.com/gorilla/schema.TestSlices(,0xc420074750)
	/Users/kurt/gopath/src/example.com/x/vendor/github.com/gorilla/schema/encoder_test.go:161, +0x2ec
testing.tRunner(0xc420074750,, 0x11764e0)
	/usr/local/Cellar/go/1.8.1/libexec/src/testing/testing.go:657, +0x96
created by testing.(*T).Run,
	/usr/local/Cellar/go/1.8.1/libexec/src/testing/testing.go:697 +0x2ca
Error: Tests failed.
```

**Comment by kisielk** [comment]
Can you provide a runnable example, as text?

**Comment by kurtzhong** [comment]
@kisielk  sure
```
package main

import (
	"github.com/gorilla/schema"
)

type S struct{ F01 *inner }

type inner struct{ F02 int }

func main() {
	s := S{
		F01: &inner{2},
	}
	vals := make(map[string][]string)
	schema.NewEncoder().Encode(s, vals)
}

```

**Comment by LeonB** [comment]
The commit 4663607285146df46a987f5e930bdfbd2d7cbe96 broke custom encoders for struct pointers. I've added a test to replicate this behavior in c9eb2ed342b7fed9e5fbd3004c49f59871d61a14.

The problem is that `*schema.builtinEncoderStructPointerOverridden` is registered as a custom encoder  `e.regenc`. However because of this code in `encoder.go`:

``` go
		if isValidStructPointer(v.Field(i)) {
			e.encode(v.Field(i).Elem(), dst)
			continue
		}
```

the field value is converted to the non-pointer type and therefore the type can't be found in the `e.regenc` map.

I'm not sure how to fix it though.

**Comment by LeonB** [comment]
I 've adjusted encoder.go to pass all tests: 98621ae21a8e51f0b10b144d8c48591a6e287b3e

But I'm not exactly sure if this is the best way.

**Comment by kisielk** [comment]
@LeonB I'm confused, where are these commits? I don't see them in a PR but somehow they're in this repo?

**Comment by LeonB** [comment]
Yeah, looks like some weird github issue/feature. The commits are actually here: https://github.com/tim-online/schema

**Comment by LeonB** [comment]
Should I add a PR?

@keeszorge

**Comment by 0syntrax0** [comment]
Issue is still happening :(.
